server:
  port: 9001

spring:
  application:
    name: Department-Service

eureka:
  client:
    register-with-eureka: true
    fetch-regsitry: true
    serive-url: http://localhost:8761/eureka/
  instance:
    hostname: localhost