server:
  port: 9002

spring:
  application:
    name: User-Service

eureka:
  client:
    register-with-eureka: true
    fetch-regsitry: true
    serive-url: http://localhost:8761/eureka/
  instance:
    hostname: localhost